site_name: Danish Language Resources
site_description: Resources and information for English-speakers learning Danish
site_author: James P. Howard, II
copyright: Copyright &copy; 2015&mdash;2021 James P. Howard, II.
site_url: https://jamesohward.us/danish-language-resources

repo_name: 'k3jph/danish-language-resources'
repo_url: https://github.com/k3jph/danish-language-resources

use_directory_urls: true

nav:
  - Welcome: index.md
  - Memrise: memrise.md
  - DanishClass101: danishclass101.md
  - Danish Lessons with Marty: marty.md
  - Podcasts: podcasts.md
  - Chat: chat.md
  - Playlists: playlists.md
  - Humor: humor.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'grey'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# Google Analytics
google_analytics:
  - 'UA-79581-13'
  - 'auto'

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.details
  - toc:
      permalink: true

plugins:
  - search